apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
  labels:
    app: flask-bucketlist
type: Opaque
stringData:
  MYSQL_DATABASE_USER: "root"
  MYSQL_DATABASE_PASSWORD: "root"
  MYSQL_ROOT_PASSWORD: "root"
