apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-app-monitor
  namespace: monitoring
  labels:
    release: my-prometheus
spec:
  selector:
    matchLabels:
      app: nodejs
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: nodejs
    path: /metrics
    interval: 15s
