services:
  # 1. Java Spring Boot Application (Listening internally on 6666)
  java-app:
    build: ./spring-prometheus-demo
    container_name: java-spring-app
    ports:
      - "6666:6666"
    restart: always

  # 2. Node.js Application (Listening internally on 8000)
  nodejs-app:
    build: ./nodejs-app-for-prometheus
    container_name: nodejs-prometheus-app
    ports:
      - "3000:8000"
    restart: always

  # 3. Google cAdvisor (Container Resource Telemetry Engine)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - "8085:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: always
