global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'server_vm'
    static_configs:
      - targets: ['<IP_OF_OTHER_VM>:9100']

  - job_name: 'python_flask_app'
    static_configs:
      - targets: ['<IP_OF_PYTHON_APP_VM>:5000']

  - job_name: 'ec2_node_exporter'
    static_configs:
      - targets: ['<PUBLIC_OR_PRIVATE_IP_OF_EC2>:9100']

  - job_name: 'containerized_nodejs_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['<IP_OF_DOCKER_NODE_VM>:3000']

  - job_name: 'containerized_java_spring_boot_app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['<IP_OF_DOCKER_NODE_VM>:6666']

  - job_name: 'containerized_cadvisor_metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['<IP_OF_DOCKER_NODE_VM>:8085']
